# Generated by Django 3.0.3 on 2020-02-28 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('location', models.TextField(max_length=360)),
                ('url', models.TextField(max_length=360)),
                ('description', models.CharField(max_length=32)),
                ('type', models.CharField(max_length=32)),
                ('projects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
