# Generated by Django 3.0.3 on 2020-03-02 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_auto_20200228_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='isPublic',
            field=models.BooleanField(default=True),
        ),
    ]
