sudo: required
services:
    - docker

before_install:

script:
  - docker-compose up --build --force-recreate
  - docker-compose down

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push dockerhub:latest
