sudo: required
services:
    - docker

before_install:

script:
  - docker-compose build yilaisjsu/machinelearningstudio

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push dockerhub:latest
