version: '3'

services:
  redis:
    image: "redis:alpine"
  web:
    build: .
    command: bash -c "python /code/manage.py migrate --noinput && python /code/manage.py runserver --noreload 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis
  celery:
    build: .
    command: watchmedo auto-restart --pattern=*.py --recursive -- celery -A  celery_tasks.tasks worker -l info --concurrency=1 --loglevel=INFO
    volumes:
      - .:/code
    depends_on:
      - redis